### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by mekarpeles**

### CODE REVIEW

**Review by cclauss — APPROVED** [review]

**Comment by hornc** [comment]
**Informational:** This change has been merged into the https://github.com/internetarchive/infogami fork here: https://github.com/internetarchive/infogami/pull/3

**Comment by cclauss** [comment]
This is a simple, obvious typo change.  Why not just review it, approve it, and land it?

**Comment by mekarpeles** [comment]
Cc: @anandology do you have write access?

**Comment by cclauss** [comment]
Oh.  Sorry.  I did not notice that this is a PR on upstream.

**Comment by mekarpeles** [comment]
closing as internetarchive/infogami seems to be the version we're going with moving forward

**Pull request closed without merging**
